version: 2
jobs:
  build:
    docker:
      - image: damacus/docker-chefdk
    working_directory: ~/project
    steps:
      - checkout
      - setup_remote_docker:
          version: 17.11.0-ce
      - run:
          name: Build image
          command: |
            KITCHEN_LOCAL_YAML=.kitchen.dokken.yml kitchen list
            KITCHEN_LOCAL_YAML=.kitchen.dokken.yml kitchen test client-centos-7 
workflows:
  version: 2
  build:
    jobs:
      - build
