defaults: &defaults
  working_directory: /home/project
  docker:
    - image: damacus/docker-chefdk


version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      # - setup_remote_docker:
      #     version: 17.11.0-ce
      - run:
          name: Setup ChefDK
          command: |
            curl -L https://www.opscode.com/chef/install.sh | bash -s -- -P chefdk
            echo 'eval "$(chef shell-init bash)"' >> ~/.bashrc
      - run:
          name: Check kitchen config is valid
          command: KITCHEN_LOCAL_YAML=.kitchen.dokken.yml kitchen list
      # - persist_to_workspace:
      #     root: /home
      #     paths:
      #       - project
  #
  # unit_test:
  #   <<: *defaults
  #   steps:
  #     - attach_workspace:
  #         at: /home/project
  #     - run:
  #         name: Unit Test
  #         command: chef exec delivery local all
  #
  # test_client-amazonlinux:
  #   <<: *defaults
  #   steps:
  #     - run:
  #         name: Dokken Test
  #         command: KITCHEN_LOCAL_YAML=.kitchen.dokken.yml kitchen test client-amazonlinux


workflows:
  version: 2
  build:
    jobs:
      - build
      # - unit_test:
      #     requires:
      #       - build
