version: 2
jobs:
  build:
    docker:
      - image: damacus/docker-chefdk
    working_directory: ~/project
    steps:
      - checkout
      - setup_remote_docker:
          version: 17.11.0-ce
      - run:
          name: Build image
          command: |
            KITCHEN_LOCAL_YAML=.kitchen.dokken.yml kitchen list

  test_client-amazonlinux:
    docker:
      - image: damacus/docker-chefdk
    steps:
      - run:
        name: Dokken Test
        command: KITCHEN_LOCAL_YAML=.kitchen.dokken.yml kitchen test client-amazonlinux

  test_client-debian-7:
    docker:
      - image: damacus/docker-chefdk
    steps:
      - run:
        name: Dokken Test
        command: KITCHEN_LOCAL_YAML=.kitchen.dokken.yml kitchen test client-debian-7

  test_client-debian-8:
    docker:
      - image: damacus/docker-chefdk
    steps:
      - run:
        name: Dokken Test
        command: KITCHEN_LOCAL_YAML=.kitchen.dokken.yml kitchen test client-debian-8

  test_client-debian-9:
    docker:
      - image: damacus/docker-chefdk
    steps:
      - run:
        name: Dokken Test
        command: KITCHEN_LOCAL_YAML=.kitchen.dokken.yml kitchen test client-debian-9

  test_client-centos-6:
    docker:
      - image: damacus/docker-chefdk
    steps:
      - run:
        name: Dokken Test
        command: KITCHEN_LOCAL_YAML=.kitchen.dokken.yml kitchen test client-centos-6

  test_client-centos-7:
    docker:
      - image: damacus/docker-chefdk
    steps:
      - run:
        name: Dokken Test
        command: KITCHEN_LOCAL_YAML=.kitchen.dokken.yml kitchen test client-centos-7

  test_client-fedora-26:
    docker:
      - image: damacus/docker-chefdk
    steps:
      - run:
        name: Dokken Test
        command: KITCHEN_LOCAL_YAML=.kitchen.dokken.yml kitchen test client-fedora-26

  test_client-fedora-27:
    docker:
      - image: damacus/docker-chefdk
    steps:
      - run:
        name: Dokken Test
        command: KITCHEN_LOCAL_YAML=.kitchen.dokken.yml kitchen test client-fedora-27

  test_client-ubuntu-1404:
    docker:
      - image: damacus/docker-chefdk
    steps:
      - run:
        name: Dokken Test
        command: KITCHEN_LOCAL_YAML=.kitchen.dokken.yml kitchen test client-ubuntu-1404

  test_client-ubuntu-1604:
    docker:
      - image: damacus/docker-chefdk
    steps:
      - run:
        name: Dokken Test
        command: KITCHEN_LOCAL_YAML=.kitchen.dokken.yml kitchen test client-ubuntu-1604

  test_client-opensuse-leap:
    docker:
      - image: damacus/docker-chefdk
    steps:
      - run:
        name: Dokken Test
        command: KITCHEN_LOCAL_YAML=.kitchen.dokken.yml kitchen test client-opensuse-leap

  test_server-amazonlinux:
    docker:
      - image: damacus/docker-chefdk
    steps:
      - run:
        name: Dokken Test
        command: KITCHEN_LOCAL_YAML=.kitchen.dokken.yml kitchen test server-amazonlinux

  test_server-debian-7:
    docker:
      - image: damacus/docker-chefdk
    steps:
      - run:
        name: Dokken Test
        command: KITCHEN_LOCAL_YAML=.kitchen.dokken.yml kitchen test server-debian-7

  test_server-debian-8:
    docker:
      - image: damacus/docker-chefdk
    steps:
      - run:
        name: Dokken Test
        command: KITCHEN_LOCAL_YAML=.kitchen.dokken.yml kitchen test server-debian-8

  test_server-debian-9:
    docker:
      - image: damacus/docker-chefdk
    steps:
      - run:
        name: Dokken Test
        command: KITCHEN_LOCAL_YAML=.kitchen.dokken.yml kitchen test server-debian-9

  test_server-centos-6:
    docker:
      - image: damacus/docker-chefdk
    steps:
      - run:
        name: Dokken Test
        command: KITCHEN_LOCAL_YAML=.kitchen.dokken.yml kitchen test server-centos-6

  test_server-centos-7:
    docker:
      - image: damacus/docker-chefdk
    steps:
      - run:
        name: Dokken Test
        command: KITCHEN_LOCAL_YAML=.kitchen.dokken.yml kitchen test server-centos-7

  test_server-fedora-26:
    docker:
      - image: damacus/docker-chefdk
    steps:
      - run:
        name: Dokken Test
        command: KITCHEN_LOCAL_YAML=.kitchen.dokken.yml kitchen test server-fedora-26

  test_server-fedora-27:
    docker:
      - image: damacus/docker-chefdk
    steps:
      - run:
        name: Dokken Test
        command: KITCHEN_LOCAL_YAML=.kitchen.dokken.yml kitchen test server-fedora-27

  test_server-ubuntu-1404:
    docker:
      - image: damacus/docker-chefdk
    steps:
      - run:
        name: Dokken Test
        command: KITCHEN_LOCAL_YAML=.kitchen.dokken.yml kitchen test server-ubuntu-1404

  test_server-ubuntu-1604:
    docker:
      - image: damacus/docker-chefdk
    steps:
      - run:
        name: Dokken Test
        command: KITCHEN_LOCAL_YAML=.kitchen.dokken.yml kitchen test server-ubuntu-1604

  test_server-opensuse-leap:
    docker:
      - image: damacus/docker-chefdk
    steps:
      - run:
        name: Dokken Test
        command: KITCHEN_LOCAL_YAML=.kitchen.dokken.yml kitchen test server-opensuse-leap



workflows:
  version: 2
  build:
    jobs:
      - build
      - test_client-amazonlinux:
        requires:
          - build
      - test_client-debian-7:
        requires:
          - build
      - test_client-debian-8:
        requires:
          - build
      - test_client-debian-9:
        requires:
          - build
      - test_client-centos-6:
        requires:
          - build
      - test_client-centos-7:
        requires:
          - build
      - test_client-fedora-26:
        requires:
          - build
      - test_client-fedora-27:
        requires:
          - build
      - test_client-ubuntu-1404:
        requires:
          - build
      - test_client-ubuntu-1604:
        requires:
          - build
      - test_client-opensuse-leap:
        requires:
          - build
      - test_server-amazonlinux:
        requires:
          - build
      - test_server-debian-7:
        requires:
          - build
      - test_server-debian-8:
        requires:
          - build
      - test_server-debian-9:
        requires:
          - build
      - test_server-centos-6:
        requires:
          - build
      - test_server-centos-7:
        requires:
          - build
      - test_server-fedora-26:
        requires:
          - build
      - test_server-fedora-27:
        requires:
          - build
      - test_server-ubuntu-1404:
        requires:
          - build
      - test_server-ubuntu-1604:
        requires:
          - build
      - test_server-opensuse-leap:
        requires:
          - build
