defaults: &defaults
  working_directory: /home/project
  docker:
    - image: damacus/docker-chefdk


version: 2
jobs:
  build:
    steps:
      - checkout
      - setup_remote_docker:
          version: 17.11.0-ce
      - run:
          name: Check kitchen config is valid
          command: KITCHEN_LOCAL_YAML=.kitchen.dokken.yml kitchen list
      - persist_to_workspace:
          root: /home
          paths:
            - project

  unit_test:
    <<: *defaults
    steps:
      - attach_workspace:
          at: /home/project
      - run:
          name: Unit Test
          command: chef exec delivery local all

  test_client-amazonlinux:
    <<: *defaults
    steps:
      - run:
          name: Dokken Test
          command: KITCHEN_LOCAL_YAML=.kitchen.dokken.yml kitchen test client-amazonlinux

  test_client-debian-7:
    <<: *defaults
    steps:
      - run:
          name: Dokken Test
          command: KITCHEN_LOCAL_YAML=.kitchen.dokken.yml kitchen test client-debian-7

  test_client-debian-8:
    <<: *defaults
    steps:
      - run:
          name: Dokken Test
          command: KITCHEN_LOCAL_YAML=.kitchen.dokken.yml kitchen test client-debian-8

  test_client-debian-9:
    <<: *defaults
    steps:
      - run:
          name: Dokken Test
          command: KITCHEN_LOCAL_YAML=.kitchen.dokken.yml kitchen test client-debian-9

  test_client-centos-6:
    <<: *defaults
    steps:
      - run:
          name: Dokken Test
          command: KITCHEN_LOCAL_YAML=.kitchen.dokken.yml kitchen test client-centos-6

  test_client-centos-7:
    <<: *defaults
    steps:
      - run:
          name: Dokken Test
          command: KITCHEN_LOCAL_YAML=.kitchen.dokken.yml kitchen test client-centos-7

  test_client-fedora-26:
    <<: *defaults
    steps:
      - run:
          name: Dokken Test
          command: KITCHEN_LOCAL_YAML=.kitchen.dokken.yml kitchen test client-fedora-26

  test_client-fedora-27:
    <<: *defaults
    steps:
      - run:
          name: Dokken Test
          command: KITCHEN_LOCAL_YAML=.kitchen.dokken.yml kitchen test client-fedora-27

  test_client-ubuntu-1404:
    <<: *defaults
    steps:
      - run:
          name: Dokken Test
          command: KITCHEN_LOCAL_YAML=.kitchen.dokken.yml kitchen test client-ubuntu-1404

  test_client-ubuntu-1604:
    <<: *defaults
    steps:
      - run:
          name: Dokken Test
          command: KITCHEN_LOCAL_YAML=.kitchen.dokken.yml kitchen test client-ubuntu-1604

  test_client-opensuse-leap:
    <<: *defaults
    steps:
      - run:
          name: Dokken Test
          command: KITCHEN_LOCAL_YAML=.kitchen.dokken.yml kitchen test client-opensuse-leap

  test_server-amazonlinux:
    <<: *defaults
    steps:
      - run:
          name: Dokken Test
          command: KITCHEN_LOCAL_YAML=.kitchen.dokken.yml kitchen test server-amazonlinux

  test_server-debian-7:
    <<: *defaults
    steps:
      - run:
          name: Dokken Test
          command: KITCHEN_LOCAL_YAML=.kitchen.dokken.yml kitchen test server-debian-7

  test_server-debian-8:
    <<: *defaults
    steps:
      - run:
          name: Dokken Test
          command: KITCHEN_LOCAL_YAML=.kitchen.dokken.yml kitchen test server-debian-8

  test_server-debian-9:
    <<: *defaults
    steps:
      - run:
          name: Dokken Test
          command: KITCHEN_LOCAL_YAML=.kitchen.dokken.yml kitchen test server-debian-9

  test_server-centos-6:
    <<: *defaults
    steps:
      - run:
          name: Dokken Test
          command: KITCHEN_LOCAL_YAML=.kitchen.dokken.yml kitchen test server-centos-6

  test_server-centos-7:
    <<: *defaults
    steps:
      - run:
          name: Dokken Test
          command: KITCHEN_LOCAL_YAML=.kitchen.dokken.yml kitchen test server-centos-7

  test_server-fedora-26:
    <<: *defaults
    steps:
      - run:
          name: Dokken Test
          command: KITCHEN_LOCAL_YAML=.kitchen.dokken.yml kitchen test server-fedora-26

  test_server-fedora-27:
    <<: *defaults
    steps:
      - run:
          name: Dokken Test
          command: KITCHEN_LOCAL_YAML=.kitchen.dokken.yml kitchen test server-fedora-27

  test_server-ubuntu-1404:
    <<: *defaults
    steps:
      - run:
          name: Dokken Test
          command: KITCHEN_LOCAL_YAML=.kitchen.dokken.yml kitchen test server-ubuntu-1404

  test_server-ubuntu-1604:
    <<: *defaults
    steps:
      - run:
          name: Dokken Test
          command: KITCHEN_LOCAL_YAML=.kitchen.dokken.yml kitchen test server-ubuntu-1604

  test_server-opensuse-leap:
    <<: *defaults
    steps:
      - run:
          name: Dokken Test
          command: KITCHEN_LOCAL_YAML=.kitchen.dokken.yml kitchen test server-opensuse-leap



workflows:
  version: 2
  build:
    jobs:
      - build
      - unit_test:
          requires:
            - build
      - test_client-amazonlinux:
          requires:
            - build
            - unit_test
      - test_client-debian-7:
          requires:
            - build
            - unit_test
      - test_client-debian-8:
          requires:
            - build
            - unit_test
      - test_client-debian-9:
          requires:
            - build
            - unit_test
      - test_client-centos-6:
          requires:
            - build
            - unit_test
      - test_client-centos-7:
          requires:
            - build
            - unit_test
      - test_client-fedora-26:
          requires:
            - build
            - unit_test
      - test_client-fedora-27:
          requires:
            - build
            - unit_test
      - test_client-ubuntu-1404:
          requires:
            - build
            - unit_test
      - test_client-ubuntu-1604:
          requires:
            - build
            - unit_test
      - test_client-opensuse-leap:
          requires:
            - build
            - unit_test
      - test_server-amazonlinux:
          requires:
            - build
            - unit_test
      - test_server-debian-7:
          requires:
            - build
            - unit_test
      - test_server-debian-8:
          requires:
            - build
            - unit_test
      - test_server-debian-9:
          requires:
            - build
            - unit_test
      - test_server-centos-6:
          requires:
            - build
            - unit_test
      - test_server-centos-7:
          requires:
            - build
            - unit_test
      - test_server-fedora-26:
          requires:
            - build
            - unit_test
      - test_server-fedora-27:
          requires:
            - build
            - unit_test
      - test_server-ubuntu-1404:
          requires:
            - build
            - unit_test
      - test_server-ubuntu-1604:
          requires:
            - build
            - unit_test
      - test_server-opensuse-leap:
          requires:
            - build
            - unit_test
